on:
  workflow_call:

jobs:
  merge:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request' && github.actor == 'MeilCli'
    steps:
      - uses: actions/github-script@v6
        if: contains(github.event.pull_request.labels.*.name, 'Action')
        with:
          github-token: ${{ secrets.MEILCLI_BOT }}
          script: |
            github.rest.pulls.merge(
              {
                pull_number: context.payload.pull_request.number,
                owner: context.repo.owner,
                repo: context.repo.repo
              }
            )
